server:
  port: 8081
  servlet:
    context-path: /achivki

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:achievement}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1357}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:achievement}
    user: ${DB_USER:postgres}
    password: ${DB_PASS:1357}
    driver-class-name: org.postgresql.Driver
logging.level.ru.iteco.fmh: debug

#swagger:
#  host: ${SWAGGER_HOST}